name: Build

on:
  workflow_dispatch:
  push:
    branches: '**'
  pull_request:
    branches: [ main, code-action-unification ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        include:
          - runtime: linux
            os: ubuntu-latest
            reportName: linux-test-report
          - runtime: mac
            os: macOS-latest
            reportName: mac-test-report
          - runtime: windows
            os: windows-latest
            reportName: windows-test-report
    steps:
      - name: Configure pagefile
        if: contains(matrix.os, 'windows')
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 8GB
          maximum-size: 10GB
          disk-root: "C:"
      - name: Fetch source branch names of open pull requests
        id: fetch_branch_names
        shell: bash
        run: |
          BRANCHES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open" | jq -r '.[].head.ref')
          echo "Source branch names of open pull requests: $BRANCHES"
          echo "::set-output name=BRANCHES::$BRANCHES"
      - name: 'Checkout lsp4ij'
        uses: actions/checkout@v3
        with:
          repository: redhat-developer/lsp4ij
          path: lsp4ij
          ref: ${{ steps.fetch_branch_names.outputs.BRANCHES }}
      - name: 'Checkout liberty-tools-intellij'
        uses: actions/checkout@v3
        with:
          path: liberty-tools-intellij
      - name: 'Install required integration test software'
        working-directory: ./liberty-tools-intellij
        run: bash ./src/test/resources/ci/scripts/setup.sh
      - name: 'Build lsp4ij jar and publish to local Maven repository'
        working-directory: ./lsp4ij
        run: bash ./gradlew publishToMavenLocal
      - name: 'Build Liberty-Tools-Intellij'
        working-directory: ./liberty-tools-intellij
        run: bash ./gradlew buildPlugin
      - name: 'Archive artifacts'
        if: ${{ runner.os == 'Linux' && !failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: liberty-tools-intellij-${{ github.sha }}
          path: |
            ./**/*liberty-tools-intellij*.zip
            ./**/libs/*liberty-tools-intellij*.jar
          if-no-files-found: warn
          retention-days: 7
      - name: 'Run UI integration tests'
        working-directory: ./liberty-tools-intellij
        run: bash ./src/test/resources/ci/scripts/run.sh
      - name: 'Archive Test logs and reports'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.reportName }}
          path: |
            liberty-tools-intellij/build/reports/
