name: Cron Job

on:
  push: 
  workflow_dispatch:
  schedule:
    # The job runs every midnight (UTC time). Ref - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * *'

jobs:
  fetch_all_pull_request_shas:
    runs-on: ubuntu-latest
    outputs:
      shas: ${{ steps.extract.outputs.shas }}
    env:
      API_URL: https://api.github.com/repos/redhat-developer/lsp4ij/pulls
    steps:
      - name: Extract merge_commit_shas
        shell: bash
        id: extract
        run: |
          pr_infos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "${{ env.API_URL }}")

          # Extract PR numbers and merge_commit_sha values, excluding draft pull requests
          pr_details=$(echo "$pr_infos" | jq -r '.[] | select(.draft == false) | {number: .number, sha: .merge_commit_sha}')

          # Print the PR number and corresponding merge commit sha
          echo "PR number and merge commit sha:"
          echo "$pr_details" | jq -r '. | "PR #\(.number): \(.sha)"'

          # Extract merge_commit_sha values into an array
          merge_commit_shas=($(echo "$pr_details" | jq -r '.sha'))

          # Create a JSON array string
          shas=$(jq -nc --arg shas "${merge_commit_shas[*]}" '$shas | split(" ")')
          echo "shas=$shas" >> $GITHUB_OUTPUT

  # Run the LTI Tests against each open lsp4ij PR
  call-build-workflow-for-each-merge-commit-sha:
    needs: fetch_all_pull_request_shas
    uses: ./.github/workflows/build.yaml
    strategy:
      fail-fast: false
      matrix:
        sha: ${{ fromJson(needs.fetch_all_pull_request_shas.outputs.shas) }}
    with:
      useLocalPlugin: true
      refLsp4ij: ${{ matrix.sha }}

  # Run the LTI Tests against lsp4ij main branch
  call-build-workflow-for-lsp4ij-main-branch:
    uses: ./.github/workflows/build.yaml
    with:
      useLocalPlugin: true
      refLsp4ij: main